### PR TITLE
Added Custom Icon Badges

### PR DESCRIPTION
**Pull request by DenverCoder1**
* Added [Custom Icon Badges](https://github.com/DenverCoder1/custom-icon-badges) (suggested at [awesome-badges #9 (review)](https://github.com/badges/awesome-badges/pull/9#pullrequestreview-1009824083))

~* Added a new section for "Badge service utilities" as Custom Icon Badges falls into the "Dynamic data providers" category even less so than Dynamic Badge Formatter, so I felt it should maybe get a new category (this was also suggested in [shields #8082 (comment)](https://github.com/badges/shields/pull/8082#issuecomment-1157098458))~

Added to the Icons section

### CODE REVIEW

**Comment by calebcartwright** [comment]
I confess to being ambivalent on this one.

Part of me feels like we should carve out a new section for Endpoints and label it explicitly, but the icon one is trickier. I feel like one could make the case for it belonging in a number of existing sections (Icons, Dynamic Badge Services, maybe even Static Badges), or under a new section.

Thoughts @badges/shields-core?

**Comment by espadrine** [comment]
Putting myself in the shoes of someone in that use-case, I’d Ctrl+F _“icons”_, so it would make sense in that section.

(I would probably add <https://badges.pages.dev> there as well.)

**Comment by chris48s** [comment]
Yeah I'd agree with putting this and https://badges.pages.dev/ under Icons

**Comment by DenverCoder1** [comment]
I've moved it to the Icons section now.

I could also make a PR for https://badges.pages.dev/ or add it this same PR.

**Comment by calebcartwright** [comment]
> I could also make a PR for https://badges.pages.dev/ or add it this same PR.

I'm going to go ahead and merge this as-is, but certainly feel free to do that in a subsequent PR if you're up for it

**Review by calebcartwright — APPROVED** [review]
Thanks!

**Pull request merged**
